#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/supervisor" ]; then
	invoke-rc.d supervisor stop || exit $?
fi
# End automatically added section
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules -c  supervisor.public
fi
# End automatically added section
